# fly.toml app configuration file generated for gingerkiwi-2024 on 2023-11-25T11:28:04-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gingerkiwi-2024"
primary_region = "yyz"

[build]

[mounts]
  source = "db"
  destination = "/mnt/db"

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
